### ISSUE TITLE
coding problem!

### ISSUE THREAD

**Issue by Hab5Fan31** [Hab5Fan31/masthead-semantics#1]
I have a problem with my assignment can you check it out for me I cant move forward to the next if I don't know what to do.
I'm trying to attach the folder but its not letting me select it..
@thomasjbradley

**Comment by thomasjbradley** [comment]
Markbot is pointing out an error on line 27, have a look at the line above and see if there is a problem with the code.

**Comment by Hab5Fan31** [comment]
Thank you! fixed it ! i forgot to close the img
